### ISSUE TITLE
Unclear sentence

### ISSUE THREAD

**Issue by webgodo** [farakavco/blueprint#3]
In the **HTML** section, there is something unclear (to me):
```
Avoid using "style,link,script" tag, Except for refrence to external resource.
```

Please make it more bright.

**Comment by pylover** [comment]
Nice
On Mar 8, 2016 5:53 PM, Mohsen <notifications@github.com> wrote:In the HTML section, there is something unclear (to me):

Avoid using "style,link,script" tag, Except for refrence to external resource.

Please make it more bright.
